### ISSUE TITLE
Feature: Please create a helm repo for this chart

### ISSUE THREAD

**Issue by zerthimon** [manticoresoftware/manticoresearch-helm#1]
It can be done with github pages.  
Example: https://harness.io/blog/devops/helm-chart-repo/

**Comment by Nick-S-2018** [comment]
This is a test comment for Syncer

**Comment by ksa-real** [comment]
Would you guys take a look at the example? Looks pretty straightforward to implement.

**Comment by sanikolaev** [comment]
Yes, thanks for pushing this.

**Comment by ksa-real** [comment]
I went ahead and tried this in my own repo. The actions are:
- Add orphan `gh-pages` branch.
- Add initial commit, e.g. like this: https://github.com/moodby/manticoresearch-helm/commit/c3dacae3147987b46e24bc6c74d0af9bdbc108cf
- Push the branch.
- Go Project Settings/Pages. Use default: Setup from branch, use `gh-pages` branch and `root` path. At this point you should have working Github pages.
- Required chart changes: https://github.com/manticoresoftware/manticoresearch-helm/pull/20

**Comment by githubmanticore** [comment]
➤ Klim Todrik commented:
 

 
Done
