### ISSUE TITLE
Deployment to multiple namespaces fail because of ClusterRole conflict

### ISSUE THREAD

**Issue by ksa-real** [manticoresoftware/manticoresearch-helm#12]
As ClusterRole and ClusterRoleBinding are not namespaced, an attempt to deploy to different namespaces (e.g. dev and stage) with the same release name fails. A temporary solution would be adding `{{ .Release.Namespace }}` to the names to avoid the conflict ([link](https://github.com/viplay-media/manticoresearch-helm/commit/248ba847df49e7f85eda511aac8c238b774c89ef)).  
  
Not sure about the longer-term one.  Getting nodes' information cluster-wide seems unnecessary for the balancer. Two options to consider:  
- Getting node resources directly from workers within a namespace.  
- Creating K8s operator, that manages releases cluster-wide. (Likely unnecessary as a simple StatefulSet scaling seems to work).  
What do you think?

**Comment by sanikolaev** [comment]
@ksa-real This is a good finding. We've discussed it and your changes looks great. Can you please make a pull request with it?

We need the ClusterRole to get more detailed CPU info for more optimal indexes optimization.

**Comment by ksa-real** [comment]
> We need the ClusterRole to get more detailed CPU info for more optimal indexes optimization.

This is clear. What I meant is giving the balancer access to the whole cluster seems too much. E.g. if the cluster contains many more nodes than just those containing workers. Effectively, the balancer works a bit like K8s operator having permissions (read-only) to operate on the entire cluster. Instead, worker pods probably could report CPU data from within the container. I'm not sure if this is possible to do, just an idea.

**Comment by ksa-real** [comment]
@sanikolaev

**Comment by sanikolaev** [comment]
Thank for for the PR. We are currently busy with preparing release of Manticore Search 5. We'll review and merge the PR right after that.

**Comment by githubmanticore** [comment]
➤ Klim Todrik commented:
 

 
merged
