### ISSUE TITLE
On pod startup existing cluster sometimes may not find peers

### ISSUE THREAD

**Issue by ksa-real** [manticoresoftware/manticoresearch-helm#14]
I had a situation in dev cluster where the existing cluster's workers could not connect to each other.  
  
## Steps to reproduce:  
Create a cluster with 2 workers. Kill both pod workers at the same time. E.g.:  
```  
$ kubectl delete pod manticore-worker-0 manticore-worker-1  
```  
Once pods are up and running they are no longer in the cluster and cannot connect to each other.  
  
## What happened  
Starting set of workers  (discovery IPs) are specified in `manticore.json` in `.cluster.manticore.nodes` which corresponds to `cluster_manticore_nodes_set`  status value. When another worker joins the cluster, the cluster_manticore_nodes_set is not updated. Instead, `cluster_manticore_nodes_view` is updated. The latter is not persisted. Now, imagine a cluster with 2 StatefulSet replicas. If both pods are deleted simultaneously (for some reason), these pods get new IP addresses. So, code in [replica.php](https://gitlab.com/manticoresearch/Manticore Search Helm Chart/uploads/a9997ae933130676ffba4565653fa888/1653473454_replica.php) will detect the existing cluster, and `searchd` process won't be able to connect.     
   
  
Instead, I suggest adding the code [here](https://gitlab.com/manticoresearch/Manticore Search Helm Charthttps://gitlab.com/manticoresearch/Manticore Search Helm Chart/uploads/a9997ae933130676ffba4565653fa888/1653473454_replica.php#L119) to replace the IPs with discovered IPs with the new-cluster code above.    
    
Also, [this](https://gitlab.com/manticoresearch/Manticore Search Helm Charthttps://gitlab.com/manticoresearch/Manticore Search Helm Chart/uploads/a9997ae933130676ffba4565653fa888/1653473454_replica.php#L65) doesn't seem right. As this is taking just the last digit of the instance ID, there may be some ambiguity, e.g. if there are exactly 10 or 20 workers. The key would be `0` for `manticore-pod-10` and `manticore-pod-20`. I'd suggest taking the whole number after the last dash.

**Comment by ksa-real** [comment]
@sanikolaev

**Comment by sanikolaev** [comment]
Thank you for reporting the issue. We are busy with preparing Manticore Search 5 for release now, after that we'll release all the dependant projects (various clients and this helm chart). That can alleviate some of the issues you've mentioned, in particular Manticore Search 5 is gonna be better in terms persisting cluster meta info to `manticore.json`, but some may remain. 

What can help a lot is:
* issue with a reproducible case, so it's clear how to reproduce an issue and test that it's fixed after a modification
* pull request, which a developer can review

**Comment by ksa-real** [comment]
Note that the issue is still valid with Manticore 5. I've updated the issue with steps to reproduce.

**Comment by sanikolaev** [comment]
Thank you. We'll work on this issue soon.

**Comment by ksa-real** [comment]
I want to discuss possible solutions.

First of all, workers already have a headless K8s service. So it is possible to extract a list of A/AAAA records with e.g. `dns_get_record`. Using this it is possible to know worker peers without using K8s API. Anyways, assume a pod has been restarted/deleted. The new pod with a new IP got up. Now peers in manticore.json are not actual anymore. Options:
- Run an extra script prior to `php /etc/manticoresearch/replica.php &` which will run `dns_get_record('myrelease-manticore-worker-svc', DNS_A|DNS_AAAA);`, pick either A or AAAA result records, and update `clusters.manticore.nodes` section in `manticore.json` if it was non-empty. The idea is to detect that the cluster existed at some point to fix the nodes before starting the daemon. The benefit is that manticore would just continue the previous cluster.
- Allow manticore to start and fail to detect the cluster. I guess we need to ensure (?) that no one is using a worker in standalone mode, right? Not sure what will happen if someone would be trying to do write operations against previously existing tables. Assuming a K8s healthcheck is guarding the worker, we can:
  - If this is the first pod (`myrelease-manticore-worker-0`) then either try to `JOIN CLUSTER manticore at 'myrelease-manticore-worker-1'` even for a single-replica cluster, or try to detect if such exists e.g. with `gethostbyname` or `dns_get_record`. Then if unsuccessful, try to 'CREATE CLUSTER manticore`. The issue with that we may miss the fact that the cluster previously existed. E.g. we cannot differentiate a freshly started cluster with 2 replicas from the one there both pods where simultaneously deleted. After the cluster is re-created with `CREATE CLUSTER` the tables need to be re-added to the cluster again: `alter cluster manticore add mytable`.
  - For the non-first pods we could just `JOIN CLUSTER manticore at 'myrelease-manticore-worker-1'`.

What do you think?

**Comment by githubmanticore** [comment]
➤ Klim Todrik commented:
 

 
First as I see, that use `dns_get_record` for getting pods count and them IP very bad solution. In 5 calls it give me 2-3 wrong result. Look like DNS server just don't have enough time to update records. So we need to use k8s API instead

**Comment by ksa-real** [comment]
> ➤ Klim Todrik commented:
> 
> First as I see, that use `dns_get_record` for getting pods count and them IP very bad solution. In 5 calls it give me 2-3 wrong result. Look like DNS server just don't have enough time to update records. So we need to use k8s API instead

Agree on DNS-based discovery. More [here](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id).

**Comment by githubmanticore** [comment]
➤ Klim Todrik commented:
 

 
Done
