### ISSUE TITLE
Improvements to Helm chart: labels, versioning.

### ISSUE THREAD

**Issue by ksa-real** [manticoresoftware/manticoresearch-helm#17]
I suggest using a more consistent labeling and versioning schema. This is somewhat opinionated, see below.    
    
### Labels    
While I find standard labels pretty awful and inconvenient, AFAIS most helm charts follow it. It's pretty hard to type, so I see some people add additional labels for convenience, usually app=app.kubernetes.io/instance but sometimes app=app.kubernetes.io/name. I think in scripts it is best to stick to recommended `app.kubernetes.io/instance`/`app.kubernetes.io/instance` effectively whatever is in services selectors. Additionally, `app.kubernetes.io/component` is often used. That fits well in your case: `app.kubernetes.io/component=balancer` and `app.kubernetes.io/component=worker`. You already have it besides a `.../component` one. Pros: logging and monitoring subsystems wouldn't need a special case for manticore chart.    
    
You have special labels `name` and `label` in addition to mentioned above:    
- name: for svc/catalog-manticore-balancer-svc, svc/catalog-manticore-worker-svc, deploy/catalog-manticore-balancer, sts/catalog-manticore-worker.    
- label: for sts/catalog-manticore-worker    
    
I propose:    
- Remove the 'label' label. At the moment it is used to (incorrectly) identify workers. Identification doesn't work if there is more than one release in a namespace.    
- Rename `name` to `app` or delete it altogether. While both are non-standard, I saw a number of charts recently using `app` label.    
- Use common labels in selectors and pod templates (`app.kubernetes.io/(name|instance|controller)`). Searching for a single label theoretically should be a bit more effective. On the other hand, I see that the absolute majority of sK8s services in my list (order of 100) use multiple labels with ~90% of them using standard ones (probably >70% of Helm charts if I remove those under our control).    
- Add `app.kubernetes.io/component`   
  
### Existing bug  
Mentioned in comment in #16.  
Workers have these labels:  
- label=manticore-worker  
- name=myrelease-manticore-worker  
  
`getManticorePods` selects worker pods by `label` label. If there are multiple Helm releases (e.g. `r1` and `r2`, 2 workers each) in the same namespace, the balancer would retrieve non-owned pods. In this case, both `r1` and `r2` would retrieve the same 4 pods.  
    
### Versioning    
App version is right now equal to 5.0.0.2 and the chart version is 5.0.02. The last `02` component looks pretty weird. I propose to switch to 3 component versioning or even semver. Semver is already required for charts and extra digit won't do much from the app perspective.

**Comment by githubmanticore** [comment]
➤ Klim Todrik commented:
 

 
About versioning. Yes 5.0.02 some confusing. But here `5.0.0` is ManticoreSearch version and last digit `2` - chart patch version... 
 
About labels - in progress to implement your suggestions

**Comment by ksa-real** [comment]
About versioning: yes, I understood why is that. That's why the proposal was to switch ManticoreSearch to 3-components versioning. Frankly, I don't see much value in 4 components. Typically you'll just increment the "patch" (3rd) component, and sometimes minor in terms of [Semantic Versioning](https://semver.org/). You don't necessarily need to follow the SemVer in terms of components meaning, but generally, it works well and is common nowadays.

**Comment by sanikolaev** [comment]
> Typically you'll just increment the "patch" (3rd) component, and sometimes minor in terms of [Semantic Versioning](https://semver.org/).

It's important for us to reflect the underlying Manticore Search's version in the helm chart's version, so the first 3 components are reserved including the "patch" component. When we made the decision to version the helm chart as `x.y.zi` I don't remember exactly why we didn't make it `x.y.z-i` or such, but there was some reason. The possible reasons could be:
* according to semver2 `-i` is "pre-release version", but in our case it's not a pre-release, it's a release
* there's also "Build metadata MAY be denoted by appending a plus sign", so it could be `x.y.z+i`, but "two versions that differ only in the build metadata, have the same precedence", but it's not what we want.
* there's also Helm specifics https://gitlab.com/gitlab-org/charts/gitlab/-/issues/1917 which could cause some issue then.

@ksa-real If you can suggest a way how we can change the versioning better, so that it's clear:
* what the underlying Manticore Search is
* and the version of the chart itself

I'll appreciate it.

**Comment by ksa-real** [comment]
Technically Helm requires **chart** version to be semver compliant. At this moment `5.0.02` is not. See [here](https://semver.org/#spec-item-2)
> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and **MUST NOT contain leading zeroes**.

At the same time the application version don't need to follow SemVer but may. E.g. ManticoreSearch versions may be 5.0.0, 5.0.1, 5.0.2, 5.1.0 ... I'd just use 3 components but it's totally up to you.

So far I've seen two common approaches on the versioning chart:
- Independent versions. This allows you to do chart updates without bumping the application image. E.g. you can use chart 5.2.1  and ManticoreSearch image 5.0.3 (5 here is coincidental or not - up to you). I think this is most reasonable assuming the chart and image are effectively independent modules.
- Tight coupling of chart and application version. I.e. chart version is always or almost always equal to the application version. For this one, your application should follow SemVer.

Note the versioning precedence: [item 10](https://semver.org/#spec-item-10) and [item 11](https://semver.org/#spec-item-11). E.g. `5.0.0-1` is a pre-release version to release `5.0.0` with identifier `1`. As such `5.0.0-1` is lower than `5.0.0`. One more component is metadata after `+`, but it is ignored in comparison. With the pre-set components meaning I wouldn't map 4-component app version into 3 / 4-component chart version. IMO the above approaches are better.

**Comment by sanikolaev** [comment]
So the options are:
1. leave the version as is:
  - `5.0.02` meaning `5.0.0` as the underlying Manticore Search version + suffix `2` showing the chart's version
  - just `5.0.2` when there's no patch to the chart yet
2. or decouple the versions

If we go with the 2nd option we'll lose the value of Manticore Search version as a part of the chart version. Is the value significant or not? Not sure, but as long as it's been working fine with the existing helm versions I prefer this to the 1st option despite that it looks weird and is not technically semver2.

**Comment by ksa-real** [comment]
IMO the best is to switch ManticoreSearch versioning to 3 components (SemVer). Then you can have (1) without weird prefix.

Also you have problems mapping e.g. 5.0.10.2 and 5.0.1.11. The former maps to 5.0.102, the latter to 5.0.111. The latter would be higher than former. Or 5.0.2.1/5.0.21 vs 5.0.1.10/5.0.110. Which chart is higher?

**Comment by sanikolaev** [comment]
> Also you have problems mapping e.g. 5.0.10.2 and 5.0.1.11.

Let's solve this problem when we have it. Chances are we'll never have `x.y.<z > 9>` since for the last 5 years we've never had.

**Comment by ksa-real** [comment]
Your call.

**Comment by githubmanticore** [comment]
➤ Klim Todrik commented:
 

 
Done in 9e9119a0482aa6c26e82532166022d5eeba62fdf
