### ISSUE TITLE
Helm repo add manticoresearch [URL] throws a 404

### ISSUE THREAD

**Issue by yunusdemir** [manticoresoftware/manticoresearch-helm#25]
When following instructions as follows on the [GH Pages of this repo](https://manticoresoftware.github.io/manticoresearch-helm/) and doing `helm repo add manticoresearch https://manticoresoftware.github.io/manticoresearch-helm`, Helm will throw an error:  
`Error: looks like "https://manticoresoftware.github.io/manticoresearch-helm" is not a valid chart repository or cannot be reached: failed to fetch https://manticoresoftware.github.io/manticoresearch-helm/index.yaml : 404 Not Found`  
  
Using Helm V3.9.4

**Comment by sanikolaev** [comment]
@yunusdemir the GH pages is still in progress. How did you find it? :)

Please follow the old installation instruction for the time being - https://github.com/manticoresoftware/manticoresearch-helm#install

**Comment by yunusdemir** [comment]
Well, fair enough then hahaha

I found it via the environments tab in the right sidebar, and by a bit of coincidence I just found an article on how to publish charts via GH pages

Thanks for the swift reply!

**Comment by githubmanticore** [comment]
➤ Sergey Nikolaev commented:
 

 
I've unpublished the site for now. Obviously we should have published it when it's fully tested. Thank you for pointing out the issue with that.
