### ISSUE TITLE
Expose and change default HA strategy

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-helm#41]
As discussed on call let's change this https://github.com/manticoresoftware/manticoresearch-helm/blob/master/sources/manticore-balancer/observer.php#L103  
  
so:  
* it's exposed to `values.yaml`, so users can change it  
* the default it changed from rounrobin to nodeads since it should increase the HA

**Comment by githubmanticore** [comment]
➤ Klim Todrik commented:
 

 
Done in https://github.com/manticoresoftware/manticoresearch-helm/pull/43
