### ISSUE TITLE
Version Mismatch with prometheus exporter

### ISSUE THREAD

**Issue by barryhunter** [manticoresoftware/manticoresearch-helm#44]
Have a test installation of manticoresearch-helm, that currently using 5.0.20    (know there is a 5.0.2.5 not tried that yet)   
  
Just added  
    exporter:  
      enabled: true  
  
But that seems to be trying to pull a `5.0.2.0` of exporter as well as well! Message from kubernetes:  
  
    ImagePullBackOff (Back-off pulling image "manticoresearch/prometheus-exporter:5.0.2.0")  
  
Does not seem to be anything in https://hub.docker.com/r/manticoresearch/prometheus-exporter/tags beyond 5.0.0.2  
  
Looks like values.yaml, does have a commented out 'tag'   
https://github.com/manticoresoftware/manticoresearch-helm/blob/master/charts/manticoresearch/values.yaml#L137  
  
  
Not sure if the intention is/was to release a new `prometheus-exporter` tag/image for every new `prometheus-helm` version, or is there some problem with hardcoding say 3.6.0.0 in the version?  
  
Or should we be somehow fixing the tag (manticoresearch/prometheus-exporter:3.6.0.0 seems to be working on a seperate non help installataton)

**Comment by githubmanticore** [comment]
➤ Klim Todrik commented:
 

 
1) I was build missing images 5.0.0.0 -> 5.0.2.5 
2) I was hardcoded exporter default image to [our Helm](https://github.com/manticoresoftware/manticoresearch-helm/pull/45) (not released yet)

**Comment by githubmanticore** [comment]
➤ Sergey Nikolaev commented:
 

 
I don't understand the status of this issue and why it's close, because you said "not released yet" and I see the open pull request https://github.com/manticoresoftware/manticoresearch-helm/pull/45 
 
I'm reopening it.

**Comment by githubmanticore** [comment]
➤ Klim Todrik commented:
 

 
- To fix this issue we don't need to make a new release (just build missing images) 
- In the next releases, I removed version dependency between MS Helm and Exporter (the next MS Helm version will depend on 5.0.2.5 Exporter version, so we don't need to build Exporter for any release again)
