### ISSUE TITLE
manticore should listen on UNIX Domain socket

### ISSUE THREAD

**Issue by zerthimon** [manticoresoftware/manticoresearch-helm#5]
This line is needed in the configmap: `listen = /var/run/mysqld/mysqld.sock:mysql` to `mysql` command to work.  
```  
kubectl -n manticore exec -i manticoresearch-worker-0 -- mysql < index-create.sql  
```

**Comment by djklim87** [comment]
Usually we run `mysql -h0 -P9306 < index-create.sql` or http request

**Comment by githubmanticore** [comment]
➤ Klim Todrik commented:
 

 
Done. Since 4.2.0.0
