### ISSUE TITLE
Add CLT tests

### ISSUE THREAD

**Issue by githubmanticore** [manticoresoftware/manticoresearch-helm#63]
Add [CLT](https://github.com/manticoresoftware/clt) tests to the CI

**Comment by djklim87** [comment]
We decided try to use [this](https://k3d.io/v5.6.0/) feature for our tests

**Comment by djklim87** [comment]
https://github.com/marketplace/actions/actions-k3s

**Comment by djklim87** [comment]
done in b5d80a2c1f09b9cde16856d7c83b72e5562325a6

**Comment by sanikolaev** [comment]
@djklim87 pls provide some info on the added CLT tests. What do they test?

**Comment by djklim87** [comment]
- [ ] add regex for show status query

**Comment by djklim87** [comment]
I wrote tests for:
- helm install package
- wait for deploy
- show status at 0 and 1 nodes
- create tables and add them into cluster
- simple queries via balancer to cluster tables
