### ISSUE TITLE
optimize.php will crash if percolate index is present

### ISSUE THREAD

**Issue by Dlahacz** [manticoresoftware/manticoresearch-helm#68]
Hi,
optimizer fails with error
```
RuntimeException: Can't get chunks count
```
if there is non RT index in the cluster. 

At this line https://github.com/manticoresoftware/manticoresearch-helm/blob/master/sources/manticore-balancer/optimize.php#L118 it should iterate just over RT tables.

**Comment by Dlahacz** [comment]
I need to merge this https://github.com/manticoresoftware/manticoresearch-auto-replication/pull/10 to implement fix for this issue.

**Comment by djklim87** [comment]
@Dlahacz You also need to implement PR with setting $typeFilter [there](https://github.com/manticoresoftware/manticoresearch-helm/blob/master/sources/manticore-balancer/optimize.php#L118)

**Comment by Dlahacz** [comment]
Thanks, I'll create PR later today

**Comment by djklim87** [comment]
> I've created draft PR #69 i think thats it. But i didn't test it yet.

I'll do it myself. There were some enhancements

**Comment by Dlahacz** [comment]
Ok, I'll close my draft then.

**Comment by djklim87** [comment]
Done since 6.2.12.2
