### ISSUE TITLE
Linking to dev packages is dangerous

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-helm#85]
We recently made a cleanup (removed packages older than 2 months) of our dev repositories at https://repo.manticoresearch.com/ which broke installation of the helm chart since it's linked to dev e.g. here:
https://github.com/manticoresoftware/manticoresearch-helm/blob/b5f18599949c2f4d7ac09b07770038ea0111ca94/sources/manticore-worker/Dockerfile#L1

We need to find a better way.

**Comment by djklim87** [comment]
This build include hostname fixes. https://github.com/manticoresoftware/manticoresearch-helm/pull/60/files

But I cant find related issue. I agree that using dev builds are dangerous, but here we haven't another ways here

**Comment by sanikolaev** [comment]
As discussed, linking to dev was not as it was planned initially. We are going to link it to a release docker image which refers to packages in a release repository where we don't have to do cleanups. Closing as done.
