### ISSUE TITLE
Incorrect tests after CLT version update

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/manticoresearch-helm#92]
After updating the CLT version, some issues appeared in tests that were not shown before on the old version due to a bug. 

We should investigate the reason for this and fix the CLT tests to the proper ones.

This can be done in this pull request: https://github.com/manticoresoftware/manticoresearch-helm/pull/91

<img width="460" alt="image" src="https://github.com/manticoresoftware/manticoresearch-helm/assets/59067742/5986c215-2a6b-4ed0-b22c-c2f25b91df43">

**Comment by djklim87** [comment]
Fixed and merged https://github.com/manticoresoftware/manticoresearch-helm/commit/1c5ecb2d88fbb5b5334d680aa33983491bc0138c
