### ISSUE TITLE
helm install ,pod CrashLoopBackOff

### ISSUE THREAD

**Issue by FriskKiddo** [manticoresoftware/manticoresearch-helm#96]
helm install manticore, pod status is CrashLoopBackOff. And the kubectl log output are:

Columnar version mismatch
Lib columnar not installed
Secondary columnar not installed
--2024-07-11 17:01:04--  http://repo.manticoresearch.com/repository/manticoresearch_jammy_dev/dists/jammy/main/binary-amd64/manticore-columnar-lib_2.2.5-230928-b8be4eb_amd64.deb
Resolving repo.manticoresearch.com (repo.manticoresearch.com)... 49.12.119.254
Connecting to repo.manticoresearch.com (repo.manticoresearch.com)|49.12.119.254|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-07-11 17:01:04 ERROR 404: Not Found.

**Comment by sanikolaev** [comment]
Are you sure you are not using an old dev version? In your output it refers to the dev repository which we clean from time to time.

**Comment by sanikolaev** [comment]
>  an old dev version

Or perhaps just an older release which was bound to a dev version of Manticore packages.

**Comment by sanikolaev** [comment]
OK. I'm closing this issue then. We've discussed with the dev team how we can make things more stable in the long-term run.
